### ISSUE TITLE
Duplicated "sevastopol" id

### ISSUE THREAD

**Issue by weijia-cheng** [standardebooks/leo-tolstoy_short-fiction_louise-maude_aylmer-maude_nathan-haskell-dole_constance-garnett_j-d-duff_l#2]
After some of the pre-publication changes, the `sevastopol` id got duplicated across the three Sevastopol sketches.

```
┏━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Code  ┃ Severity ┃ File        ┃ Message                                                   ┃
┡━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ x-017 │ Error    │ content.opf │ Duplicate value for id attribute. id attribute values     │
│       │          │             │ must be unique across the entire ebook on all elements    │
│       │          │             │ that do not have epub:type of volume, division, or part.  │
├───────┼──────────┼─────────────┼───────────────────────────────────────────────────────────┤
│       │          │           → │ sevastopol                                                │
└───────┴──────────┴─────────────┴───────────────────────────────────────────────────────────┘
```

Not sure how you would fix this. I guess you could make the individual sketches "parts" of `sevastopol`, or just take out `sevastopol.xhtml` and make the individual sketches top-level stories.

**Comment by acabal** [comment]
This is a problem, because `<article>` can't have the `part` semantic. But we have to use `<article>` because the item is an independent work in a larger collection.  I think the only solution is to merge all of the files into file with a top level `<article>` element. Can you see if you can make that happen?
